package br.ufrn.imd.web2.projeto1;

import java.util.Arrays;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
 
@ManagedBean(name="user")
@SessionScoped
public class UserBean{
 
	public boolean rememberMe;

	public boolean isRememberMe() {
		return rememberMe;
	}

	public void setRememberMe(boolean rememberMe) {
		this.rememberMe = rememberMe;
	}

	public String[] favNumber2;

	public String[] getFavNumber2() {
		return favNumber2;
	}

	public void setFavNumber2(String[] favNumber2) {
		this.favNumber2 = favNumber2;
	}

	//Generated by Array
	public String[] getFavNumber2Value() {
		
		favNumber2 = new String[5];
		favNumber2[0] = "Materia - 1";
		favNumber2[1] = "Materia - 2";
		favNumber2[2] = "Materia - 3";
		favNumber2[3] = "Materia - 4";
		favNumber2[4] = "Materia - 5";
		
		return favNumber2;
	}
	
	public String getFavNumber2InString() {
		return Arrays.toString(favNumber2);
	}
		
}